export const storefrontCategories = [
  "Remote Control Toys",
  "Gun & Blasters",
  "Educational & Learning Toys",
  "Games & Indoor Toys",
  "Dolls & Soft Toys",
  "Role Play & Kitchen Toys",
  "Outdoor & Sports Toys",
  "Baby & Small Toys",
  "Water & Pool Toys",
  "Creative & Hobby Toys",
  "Party & Fun Toys",
  "Vehicles & Cars",
] as const;

export const homepageCategories = [
  {
    label: "Cars / RC",
    routeLabel: "Remote Control Toys",
    href: "/products?category=Remote%20Control%20Toys",
    icon: "/assets/categories/premium/cars-rc.png",
    toneClassName: "from-[#fff8fe] to-[#f7f0ff]",
    imageClassName: "scale-[1.35] object-[center_54%]",
  },
  {
    label: "Guns",
    routeLabel: "Gun & Blasters",
    href: "/products?category=Gun%20%26%20Blasters",
    icon: "/assets/categories/premium/guns.png",
    toneClassName: "from-[#fffaf0] to-[#fff1dd]",
    imageClassName: "scale-[1.28] object-[center_58%]",
  },
  {
    label: "Learning",
    routeLabel: "Educational & Learning Toys",
    href: "/products?category=Educational%20%26%20Learning%20Toys",
    icon: "/assets/categories/premium/learning.png",
    toneClassName: "from-[#fbfff5] to-[#eff9dc]",
    imageClassName: "scale-[1.24] object-[center_56%]",
  },
  {
    label: "Games",
    routeLabel: "Games & Indoor Toys",
    href: "/products?category=Games%20%26%20Indoor%20Toys",
    icon: "/assets/categories/premium/games.png",
    toneClassName: "from-[#faf8ff] to-[#f2edff]",
    imageClassName: "scale-[1.22] object-[center_56%]",
  },
  {
    label: "Dolls",
    routeLabel: "Dolls & Soft Toys",
    href: "/products?category=Dolls%20%26%20Soft%20Toys",
    icon: "/assets/categories/premium/dolls.png",
    toneClassName: "from-[#fff9fb] to-[#fff1f7]",
    imageClassName: "scale-[1.3] object-[center_55%]",
  },
  {
    label: "Kitchen",
    routeLabel: "Role Play & Kitchen Toys",
    href: "/products?category=Role%20Play%20%26%20Kitchen%20Toys",
    icon: "/assets/categories/premium/kitchen.png",
    toneClassName: "from-[#fff9f7] to-[#fff0f4]",
    imageClassName: "scale-[1.2] object-[center_57%]",
  },
  {
    label: "Sports",
    routeLabel: "Outdoor & Sports Toys",
    href: "/products?category=Outdoor%20%26%20Sports%20Toys",
    icon: "/assets/categories/premium/sports.png",
    toneClassName: "from-[#fffdf9] to-[#f4f2ff]",
    imageClassName: "scale-[1.24] object-[center_56%]",
  },
  {
    label: "Outdoor",
    routeLabel: "Outdoor & Sports Toys",
    href: "/products?category=Outdoor%20%26%20Sports%20Toys",
    icon: "/assets/categories/premium/outdoor.png",
    toneClassName: "from-[#fbfff7] to-[#eef8db]",
    imageClassName: "scale-[1.18] object-[center_56%]",
  },
] as const;
